# docker-compose.yml (CORRECTED VERSION)

services:
  db:
    image: postgres:15
    container_name: ai_rpg_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}             # Read from .env
      POSTGRES_USER: ${POSTGRES_USER}           # Read from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}     # Read from .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: